### ISSUE TITLE
upload error with asset field 

### ISSUE THREAD

**Issue by samlising** [bymayo/craft-pdf-transform#23]
When using an asset field to upload a PDF and clicking on "upload asset" (selecting asset to upload in a dialog box), an error will occur during the transform of the pdf file. It only occurs when uploading though the dialog box. However, If I drag a PDF file into the field it uploads and transforms the image properly. 

Here is the error from the weblog:

```2023-07-20 07:54:48 [web.ERROR] [ImagickException] improper image header `/home/forge/dev.santiccioli.com/storage/runtime/temp/2802430.png' @ error/png.c/ReadPNGImage/4092 {"trace":["#0 /home/forge/dev.santiccioli.com/vendor/spatie/pdf-to-image/src/Pdf.php(42): Imagick->pingImage()","#1 /home/forge/dev.santiccioli.com/vendor/bymayo/pdf-transform/src/services/PdfTransformService.php(117): Spatie\\PdfToImage\\Pdf->__construct()"```

I have worked around this problem by including the previous transformPdfsOnUpload functionality that was available in version for craft 3. When I turn off transformPdfsOnUpload, there is no error when clicking on "upload asset" button.

**Comment by samlising** [comment]
is it possible to add transformPdfsOnUpload setting back into the craft 4 version of the plugin.

**Comment by green17** [comment]
We have encountered this issue also. Uploading the PDF triggers the error though, if uploaded separately, the file can be chosen and there is no error.

**Comment by jas8522** [comment]
In case someone else comes across this for this edge-case reason: 'improper image header' can also occur if the server is incapable of reaching itself. Ex: if you've blocked access to the world excluding certain IPs, but the server IP is not in that exclusion list (ie: it's not allowed).

**Comment by svonlanthen** [comment]
Should I be able to open the generated PNG-Files in f.e. Photoshop?

I cannot even upload the generated PNG here because the Header of the file seems damaged.

Thank you very much for your help.

This is the error I have:
`2025-06-04 08:18:07 [web.ERROR] [ImagickException] improper image header `/home/ideespor/public_html/dev.ideesport.ch/releases/132/storage/runtime/temp/5034199.png' @ error/png.c/ReadPNGImage/3941 {"trace":["#0 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/spatie/pdf-to-image/src/Pdf.php(44): Imagick->readImage('/home/ideespor/...')","#1 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/bymayo/pdf-transform/src/services/PdfTransformService.php(117): Spatie\\PdfToImage\\Pdf->__construct('/home/ideespor/...')","#2 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/bymayo/pdf-transform/src/PdfTransform.php(115): bymayo\\pdftransform\\services\\PdfTransformService->pdfToImage(Object(craft\\elements\\Asset))","#3 [internal function]: bymayo\\pdftransform\\PdfTransform->bymayo\\pdftransform\\{closure}(Object(craft\\events\\ElementEvent))","#4 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\\events\\ElementEvent))","#5 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/Component.php(654): yii\\base\\Event::trigger('craft\\\\services\\\\...', 'afterSaveElemen...', Object(craft\\events\\ElementEvent))","#6 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/services/Elements.php(4092): yii\\base\\Component->trigger('afterSaveElemen...', Object(craft\\events\\ElementEvent))","#7 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/services/Elements.php(1337): craft\\services\\Elements->_saveElementInternal(Object(craft\\elements\\Asset), true, true, NULL, Array, false, false, false)","#8 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/controllers/AssetsController.php(321): craft\\services\\Elements->saveElement(Object(craft\\elements\\Asset))","#9 [internal function]: craft\\controllers\\AssetsController->actionUpload()","#10 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#11 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#12 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('upload', Array)","#13 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/web/Application.php(361): yii\\base\\Module->runAction('assets/upload', Array)","#14 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/web/Application.php(660): craft\\web\\Application->runAction('assets/upload', Array)","#15 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/craftcms/cms/src/web/Application.php(323): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))","#16 /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))","#17 /home/ideespor/public_html/dev.ideesport.ch/releases/132/web/index.php(12): yii\\base\\Application->run()","#18 {main}"],"memory":5511496,"exception":"[object] (ImagickException(code: 425): improper image header `/home/ideespor/public_html/dev.ideesport.ch/releases/132/storage/runtime/temp/5034199.png' @ error/png.c/ReadPNGImage/3941 at /home/ideespor/public_html/dev.ideesport.ch/releases/132/vendor/spatie/pdf-to-image/src/Pdf.php:44)"}`

**Comment by bymayo** [comment]
This is now fixed in 5.1.0
